### ISSUE TITLE
Error opening XBMC after install

### ISSUE THREAD

**Issue by atholm** [akezeke/spotyxbmc#5] opened 2010-02-10 07:58 UTC
Hi and thanks for your work!
I have a problem after install on Ubuntu 32Bit. 
I used your install script and binary but now I cannot open XBMC.
The error is:
/usr/share/xbmc/xbmc.bin: error while loading shared libraries: libmpeg2convert.so 0: cannot open object file: No such file or directory

Thanks

**Comment by atholm** [comment] 2010-02-10 08:09
Fixed it by installing the package transcode but now a new missing file :-)
libpcrecpp.so

**Comment by atholm** [comment] 2010-02-10 08:16
And fixed that problem by installing libpcre3-dev
Maybe you should list dependencies :-)
But it seems to work quite nice. THANKS

**Comment by akezeke** [comment] 2010-02-10 08:42
Hi!

The problem is that the installation you used was not the latest, and my build is based on the latest svn. The solution is to install the dependencies suggested in the xbmc svn readme.ubuntu.

I will update my readme with this information!

/David

**Comment by atholm** [comment] 2010-02-10 10:31
Thanks for the answer :)

**Comment by akezeke** [comment] 2010-02-10 11:37
I have added the dependencies to the install script, "should" work out of the box now, closing this issue!

**Closed as completed by akezeke** 2010-02-10 11:37 UTC
